name: CopycatAction
  uses: andstor/copycat-action@v3.2.3
  with:
    personal_token: ${{ secrets.JUANS_DOCU_AUTOMATOR }}
    src_path: /.
    dst_path: /docs/didkit/
    dst_owner: bumblefudge
    dst_repo_name: /spruceid.dev/  
    src_branch: xp-tweaks
    dst_branch: automator-testing
    file_filter: "*.md"
    commit_message: automated .md update from src repos 
